driver:
  name: vagrant
  customize:
    ioapic: 'on' # this should be on if you want multiple cores
    cpus: '2'
    memory: '4096' # bumped up for Windows, 4GB is still very low.

transport:
  name: winrm
  winrm_username: vagrant
  winrm_password: vagrant

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: puppet/modules
  hiera_data_path: puppet/data
  hiera_config_path: puppet/hiera.yaml
  hiera_deep_merge: true
  vm_hostname: 'test'
  require_chef_for_busser: false
  puppet_debug: true
  puppet_verbose: true

  #http_proxy: 'http://192.168.1.3:3142' # Disable this unless you use apt-cacher-ng or something that caches

platforms:
  - name: windows
    driver:
      box: mwrock/Windows2016
      box_url: https://app.vagrantup.com/mwrock/boxes/Windows2016/versions/0.3.0/providers/virtualbox.box

suites:
  - name: wintest
    manifest: site.pp
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.6"}]
