driver:
  name: vagrant
  customize:
    ioapic: 'on' # this should be on if you want multiple cores
    cpus: '2'
    memory: '2048'

transport:
  name: sftp

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: puppet/modules
  hiera_data_path: puppet/data
  hiera_config_path: puppet/hiera.yaml
  hiera_deep_merge: true
  vm_hostname: 'test'
  require_chef_for_busser: false
  puppet_debug: false
  puppet_verbose: true
  # require_puppet_repo: false
  # puppet_logdest:
    # - 'console'
  #http_proxy: 'http://192.168.1.3:3142' # Disable this unless you use apt-cacher-ng or something that caches

platforms:
  - name: ubuntu1464
    driver:
      box: ubuntu1464-puppet
      box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-puppet/versions/1.0.3/providers/virtualbox.box
  - name: ubuntu1664
    driver:
      box: ubuntu/xenial64
      # this uses the Atlas vagrant box from 
      # https://atlas.hashicorp.com/ubuntu/boxes/xenial64

suites:
  - name: default
    manifest: site.pp
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.2"}]
    # do not build default on 14.04
    excludes:
      - ubuntu1464

  - name: tlp
    manifest: site.pp
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.2"}]
    # do not build TLP on 16.04
    excludes:
      - ubuntu1664
