driver:
  name: vagrant
  customize:
    ioapic: 'on' # this should be on if you want multiple cores
    cpus: '2'
    memory: '2048'

transport:
  name: sftp

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: puppet/modules
  hiera_data_path: puppet/data
  hiera_config_path: puppet/hiera.yaml
  hiera_deep_merge: true
  vm_hostname: 'test'
  require_chef_for_busser: false
#  require_puppet_repo: false
# puppet_logdest:
#   - 'console'
  puppet_debug: true
  puppet_verbose: true

  #http_proxy: 'http://192.168.1.3:3142' # Disable this unless you use apt-cacher-ng or something that caches

platforms:
  - name: ubuntu1664
    driver:
      box: ubuntu/xenial64
      box_url: https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-16.04-64-nocm/versions/1.0.0/providers/virtualbox.box

suites:
  - name: tac
    manifest: site.pp
    driver_config:
      network:
        - ["private_network", {ip: "192.168.10.10"}]
    excludes: 
        - ubuntu1464
        - apache-trusty
