---
driver:
  name: vagrant
  box: trusty64
  box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["forwarded_port", {guest: 443, host: 8443}]

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: puppet/modules
  hiera_data_path: puppet/data
  hiera_config_path: puppet/hiera.yaml
  require_chef_for_busser: false
  http_proxy: 'http://192.168.1.3:3142'

platforms:
  - name: ubuntu14


suites:
  - name: default
    manifest: site.pp
